[2023-07-06 15:45:54,898] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 302 0
[2023-07-06 15:45:54,926] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 4677
[2023-07-06 15:45:55,154] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 302 0
[2023-07-06 15:45:55,163] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 4677
[2023-07-06 15:46:21,826] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /ABOTestPlan/ABOTestPlan_edit/ HTTP/1.1" 200 39192
[2023-07-06 15:46:22,328] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2023-07-06 15:46:22,538] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2023-07-06 15:46:23,021] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2023-07-06 15:46:23,138] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2023-07-06 15:46:23,800] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 23410
[2023-07-06 15:46:24,273] [UserIP.py:90] [UserIP:process_response] [INFO]- 2023-07-06 15:46:24 C1010S3>Edwin None>LAPTOP-EJP4HNEV>543 127.0.0.1 127.0.0.1 /ABOTestPlan/ABOTestPlan_edit/ POST
[2023-07-06 15:46:24,286] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /ABOTestPlan/ABOTestPlan_edit/ HTTP/1.1" 200 49995
[2023-07-06 15:46:59,774] [UserIP.py:90] [UserIP:process_response] [INFO]- 2023-07-06 15:46:59 C1010S3>Edwin None>LAPTOP-EJP4HNEV>543 127.0.0.1 127.0.0.1 /ABOTestPlan/ABOTestPlan_edit/ POST
[2023-07-06 15:46:59,781] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /ABOTestPlan/ABOTestPlan_edit/ HTTP/1.1" 200 49661
[2023-07-06 16:07:19,018] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /ABOTestPlan/ABOTestPlan_edit/ HTTP/1.1" 200 39192
[2023-07-06 16:07:19,094] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2023-07-06 16:07:19,113] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2023-07-06 16:07:19,268] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2023-07-06 16:07:19,269] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2023-07-06 16:07:19,442] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 23410
[2023-07-06 16:07:19,519] [UserIP.py:90] [UserIP:process_response] [INFO]- 2023-07-06 16:07:19 C1010S3>Edwin None>LAPTOP-EJP4HNEV>543 127.0.0.1 127.0.0.1 /ABOTestPlan/ABOTestPlan_edit/ POST
[2023-07-06 16:07:19,526] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /ABOTestPlan/ABOTestPlan_edit/ HTTP/1.1" 200 49661
[2023-07-06 16:08:01,936] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /ABOTestPlan/ABOTestPlan_edit/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\ABOTestPlan\views.py", line 462, in ABOTestPlan_edit
    return HttpResponse(json.dumps(data), content_type="application/json")
  File "C:\Python372\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python372\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python372\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python372\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ValueError is not JSON serializable
[2023-07-06 16:08:01,936] [UserIP.py:90] [UserIP:process_response] [INFO]- 2023-07-06 16:08:01 C1010S3>Edwin None>LAPTOP-EJP4HNEV>543 127.0.0.1 127.0.0.1 /ABOTestPlan/ABOTestPlan_edit/ POST
[2023-07-06 16:08:01,938] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /ABOTestPlan/ABOTestPlan_edit/ HTTP/1.1" 500 103793
[2023-07-06 16:12:42,898] [UserIP.py:90] [UserIP:process_response] [INFO]- 2023-07-06 16:12:42 C1010S3>Edwin None>LAPTOP-EJP4HNEV>543 127.0.0.1 127.0.0.1 /ABOTestPlan/ABOTestPlan_edit/ POST
[2023-07-06 16:12:42,914] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /ABOTestPlan/ABOTestPlan_edit/ HTTP/1.1" 200 206
[2023-07-06 16:14:02,062] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /ABOTestPlan/ABOTestPlan_edit/ HTTP/1.1" 200 39192
[2023-07-06 16:14:02,149] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2023-07-06 16:14:02,173] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2023-07-06 16:14:02,318] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2023-07-06 16:14:02,320] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2023-07-06 16:14:02,485] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 23410
[2023-07-06 16:14:02,536] [UserIP.py:90] [UserIP:process_response] [INFO]- 2023-07-06 16:14:02 C1010S3>Edwin None>LAPTOP-EJP4HNEV>543 127.0.0.1 127.0.0.1 /ABOTestPlan/ABOTestPlan_edit/ POST
[2023-07-06 16:14:02,544] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /ABOTestPlan/ABOTestPlan_edit/ HTTP/1.1" 200 49661
[2023-07-06 16:14:28,208] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /ABOTestPlan/ABOTestPlan_edit/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\ABOTestPlan\views.py", line 443, in ABOTestPlan_edit
    save_exel(folder_path_Sys,uploaddata,upload_zhushi, filepath)
  File "C:\djangoproject\Reliability_Row_data\ABOTestPlan\views.py", line 282, in save_exel
    for key,values in i["value"]:
ValueError: too many values to unpack (expected 2)
[2023-07-06 16:14:28,215] [UserIP.py:90] [UserIP:process_response] [INFO]- 2023-07-06 16:14:28 C1010S3>Edwin None>LAPTOP-EJP4HNEV>543 127.0.0.1 127.0.0.1 /ABOTestPlan/ABOTestPlan_edit/ POST
[2023-07-06 16:14:28,218] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /ABOTestPlan/ABOTestPlan_edit/ HTTP/1.1" 500 94007
[2023-07-06 16:21:41,820] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /ABOTestPlan/ABOTestPlan_edit/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\ABOTestPlan\views.py", line 444, in ABOTestPlan_edit
    save_exel(folder_path_Sys,uploaddata,upload_zhushi, filepath)
  File "C:\djangoproject\Reliability_Row_data\ABOTestPlan\views.py", line 285, in save_exel
    df1.loc[i["row"], key].comment.text = values[2]
AttributeError: 'str' object has no attribute 'comment'
[2023-07-06 16:21:41,821] [UserIP.py:90] [UserIP:process_response] [INFO]- 2023-07-06 16:21:41 C1010S3>Edwin None>LAPTOP-EJP4HNEV>543 127.0.0.1 127.0.0.1 /ABOTestPlan/ABOTestPlan_edit/ POST
[2023-07-06 16:21:41,821] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /ABOTestPlan/ABOTestPlan_edit/ HTTP/1.1" 500 91624
