[2022-06-20 07:57:56,141] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /PersonalInfo/Summary3/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\PersonalInfo\views.py", line 6230, in Summary3
    for Per in PersonalInfoHisByYear.objects.filter(Year=YearSearch, Status__in=["離職"], QuitDate__range=Search_Endperiod):
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\lookups.py", line 210, in get_prep_lookup
    rhs_value = self.lhs.output_field.get_prep_value(rhs_value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 1268, in get_prep_value
    return self.to_python(value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 1243, in to_python
    params={'value': value},
django.core.exceptions.ValidationError: ['’‘ 必须为合法的日期格式，请使用 YYYY-MM-DD 格式。']
[2022-06-20 07:57:56,156] [UserIP.py:89] [UserIP:process_response] [CRITICAL]- 系统错误
[2022-06-20 07:57:56,157] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 500 142347
[2022-06-20 07:58:24,996] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /PersonalInfo/Summary3/ HTTP/1.1" 200 71410
[2022-06-20 07:58:25,269] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2022-06-20 07:58:25,382] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2022-06-20 07:58:25,672] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2022-06-20 07:58:25,684] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2022-06-20 07:58:26,632] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 22499
[2022-06-20 07:58:26,864] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 07:58:26 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 07:58:26,870] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 47667
[2022-06-20 07:58:30,332] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /PersonalInfo/Summary3/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\PersonalInfo\views.py", line 6219, in Summary3
    for Per in PersonalInfo.objects.filter(Status__in=["離職"], QuitDate__range=Search_Endperiod):
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\lookups.py", line 210, in get_prep_lookup
    rhs_value = self.lhs.output_field.get_prep_value(rhs_value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 1268, in get_prep_value
    return self.to_python(value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 1243, in to_python
    params={'value': value},
django.core.exceptions.ValidationError: ['’‘ 必须为合法的日期格式，请使用 YYYY-MM-DD 格式。']
[2022-06-20 07:58:30,349] [UserIP.py:89] [UserIP:process_response] [CRITICAL]- 系统错误
[2022-06-20 07:58:30,350] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 500 141415
[2022-06-20 07:59:09,678] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /PersonalInfo/Summary3/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 1230, in to_python
    parsed = parse_date(value)
  File "C:\Python372\mecheck\lib\site-packages\django\utils\dateparse.py", line 77, in parse_date
    return datetime.date(**kw)
ValueError: year 0 is out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\PersonalInfo\views.py", line 6219, in Summary3
    for Per in PersonalInfo.objects.filter(Status__in=["離職"], QuitDate__range=Search_Endperiod):
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\lookups.py", line 210, in get_prep_lookup
    rhs_value = self.lhs.output_field.get_prep_value(rhs_value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 1268, in get_prep_value
    return self.to_python(value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 1237, in to_python
    params={'value': value},
django.core.exceptions.ValidationError: ['’0000-00-00‘ 值的格式正确(YYYY-MM-DD)，但是日期无效。']
[2022-06-20 07:59:09,690] [UserIP.py:89] [UserIP:process_response] [CRITICAL]- 系统错误
[2022-06-20 07:59:09,692] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 500 149680
[2022-06-20 08:01:18,414] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 08:01:18 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 08:01:18,422] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 9000
[2022-06-20 08:01:46,322] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /PersonalInfo/Summary3/ HTTP/1.1" 200 71410
[2022-06-20 08:01:46,566] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2022-06-20 08:01:46,714] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2022-06-20 08:01:47,002] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2022-06-20 08:01:47,008] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2022-06-20 08:01:47,777] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 22499
[2022-06-20 08:01:48,115] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 08:01:48 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 08:01:48,135] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 47667
[2022-06-20 08:01:50,643] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 08:01:50 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 08:01:50,654] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 9000
[2022-06-20 08:02:08,607] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /PersonalInfo/Summary3/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\PersonalInfo\views.py", line 6219, in Summary3
    for Per in PersonalInfo.objects.filter(Status__in=["離職"], QuitDate__range=Search_Endperiod):
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\lookups.py", line 204, in get_prep_lookup
    for rhs_value in self.rhs:
TypeError: 'NoneType' object is not iterable
[2022-06-20 08:02:08,638] [UserIP.py:89] [UserIP:process_response] [CRITICAL]- 系统错误
[2022-06-20 08:02:08,655] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 500 132870
[2022-06-20 08:05:18,321] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /PersonalInfo/Summary3/ HTTP/1.1" 200 71410
[2022-06-20 08:05:18,478] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2022-06-20 08:05:18,536] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2022-06-20 08:05:18,704] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2022-06-20 08:05:18,708] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2022-06-20 08:05:19,207] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 22499
[2022-06-20 08:05:19,404] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 08:05:19 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 08:05:19,409] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 47667
[2022-06-20 08:05:47,926] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 08:05:47 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 08:05:47,936] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 9000
[2022-06-20 09:00:18,927] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 09:00:18 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 09:00:18,932] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 9000
[2022-06-20 09:00:28,206] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 09:00:28 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 09:00:28,216] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 9000
[2022-06-20 09:00:40,701] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /PersonalInfo/Summary3/ HTTP/1.1" 200 71410
[2022-06-20 09:00:41,036] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2022-06-20 09:00:41,134] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2022-06-20 09:00:41,686] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2022-06-20 09:00:41,689] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2022-06-20 09:00:42,518] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 22499
[2022-06-20 09:00:42,930] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 09:00:42 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 09:00:42,937] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 47667
[2022-06-20 09:00:45,210] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 09:00:45 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 09:00:45,220] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 9000
[2022-06-20 09:01:12,599] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /PersonalInfo/Summary3/ HTTP/1.1" 200 71410
[2022-06-20 09:01:13,126] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2022-06-20 09:01:13,270] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2022-06-20 09:01:13,921] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2022-06-20 09:01:13,924] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2022-06-20 09:01:15,022] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 22499
[2022-06-20 09:01:15,502] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 09:01:15 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 09:01:15,512] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 47667
[2022-06-20 09:01:16,605] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /PersonalInfo/Summary3/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 1230, in to_python
    parsed = parse_date(value)
  File "C:\Python372\mecheck\lib\site-packages\django\utils\dateparse.py", line 77, in parse_date
    return datetime.date(**kw)
ValueError: year 0 is out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\PersonalInfo\views.py", line 6220, in Summary3
    for Per in PersonalInfo.objects.filter(Status__in=["離職"], QuitDate__range=Search_Endperiod):
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\lookups.py", line 210, in get_prep_lookup
    rhs_value = self.lhs.output_field.get_prep_value(rhs_value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 1268, in get_prep_value
    return self.to_python(value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 1237, in to_python
    params={'value': value},
django.core.exceptions.ValidationError: ['’0000-00-00‘ 值的格式正确(YYYY-MM-DD)，但是日期无效。']
[2022-06-20 09:01:16,629] [UserIP.py:89] [UserIP:process_response] [CRITICAL]- 系统错误
[2022-06-20 09:01:16,630] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 500 149524
[2022-06-20 09:05:06,623] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /PersonalInfo/Summary3/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 1230, in to_python
    parsed = parse_date(value)
  File "C:\Python372\mecheck\lib\site-packages\django\utils\dateparse.py", line 77, in parse_date
    return datetime.date(**kw)
ValueError: year 0 is out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\PersonalInfo\views.py", line 6222, in Summary3
    for Per in PersonalInfo.objects.filter(Status__in=["離職"], QuitDate__range=Search_Endperiod):
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\lookups.py", line 210, in get_prep_lookup
    rhs_value = self.lhs.output_field.get_prep_value(rhs_value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 1268, in get_prep_value
    return self.to_python(value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 1237, in to_python
    params={'value': value},
django.core.exceptions.ValidationError: ['’0000-00-00‘ 值的格式正确(YYYY-MM-DD)，但是日期无效。']
[2022-06-20 09:05:06,639] [UserIP.py:89] [UserIP:process_response] [CRITICAL]- 系统错误
[2022-06-20 09:05:06,640] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 500 149919
[2022-06-20 09:08:01,296] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /PersonalInfo/Summary3/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\PersonalInfo\views.py", line 6216, in Summary3
    Search_start = PersonalInfo.objects.all().values("QuitDate").distinct().order_by("QuitDate").first().strftime("%Y-%m-%d")
AttributeError: 'dict' object has no attribute 'strftime'
[2022-06-20 09:08:01,310] [UserIP.py:89] [UserIP:process_response] [CRITICAL]- 系统错误
[2022-06-20 09:08:01,317] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 500 85981
[2022-06-20 09:09:08,364] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /PersonalInfo/Summary3/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\PersonalInfo\views.py", line 6224, in Summary3
    for Per in PersonalInfo.objects.filter(Status__in=["離職"], QuitDate__range=Search_Endperiod):
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\lookups.py", line 210, in get_prep_lookup
    rhs_value = self.lhs.output_field.get_prep_value(rhs_value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 1268, in get_prep_value
    return self.to_python(value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 1230, in to_python
    parsed = parse_date(value)
  File "C:\Python372\mecheck\lib\site-packages\django\utils\dateparse.py", line 74, in parse_date
    match = date_re.match(value)
TypeError: expected string or bytes-like object
[2022-06-20 09:09:08,379] [UserIP.py:89] [UserIP:process_response] [CRITICAL]- 系统错误
[2022-06-20 09:09:08,380] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 500 145226
[2022-06-20 09:10:44,836] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 09:10:44 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 09:10:44,849] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 9000
[2022-06-20 09:19:24,488] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 09:19:24 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 09:19:24,499] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 9000
[2022-06-20 09:21:08,460] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 09:21:08 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 09:21:08,470] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 47656
[2022-06-20 09:22:11,860] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 09:22:11 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 09:22:11,866] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 47656
[2022-06-20 09:56:45,700] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /PersonalInfo/Summary3/ HTTP/1.1" 302 0
[2022-06-20 09:56:45,711] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 4677
[2022-06-20 09:56:45,799] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2022-06-20 09:56:45,888] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 302 0
[2022-06-20 09:56:45,894] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/vendor/bootstrap/js/bootstrap.bundle.min.js.map HTTP/1.1" 200 303386
[2022-06-20 09:56:45,918] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 4677
[2022-06-20 09:56:47,497] [UserIP.py:89] [UserIP:process_response] [CRITICAL]- 系统错误
[2022-06-20 09:56:47,521] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /login/ HTTP/1.1" 302 0
[2022-06-20 09:56:47,643] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 47230
[2022-06-20 09:56:47,928] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2022-06-20 09:56:47,934] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 47230
[2022-06-20 09:56:48,052] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2022-06-20 09:56:48,512] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2022-06-20 09:56:48,525] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2022-06-20 09:56:48,715] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 22499
[2022-06-20 09:56:53,365] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /PersonalInfo/Summary3/ HTTP/1.1" 200 71410
[2022-06-20 09:56:53,508] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2022-06-20 09:56:53,528] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2022-06-20 09:56:53,900] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2022-06-20 09:56:53,909] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2022-06-20 09:56:54,630] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 22499
[2022-06-20 09:56:55,077] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 09:56:55 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 09:56:55,089] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 47667
[2022-06-20 09:56:58,855] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 09:56:58 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 09:56:58,866] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 47656
[2022-06-20 09:59:06,545] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 09:59:06 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 09:59:06,554] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 4093
[2022-06-20 09:59:22,576] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 09:59:22 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 09:59:22,590] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 4093
[2022-06-20 09:59:33,892] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 09:59:33 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 09:59:33,902] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 4103
[2022-06-20 10:03:14,668] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 10:03:14 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 10:03:14,681] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 4103
[2022-06-20 10:03:37,827] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 10:03:37 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 10:03:37,836] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 4103
[2022-06-20 10:04:38,845] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /PersonalInfo/Summary3/ HTTP/1.1" 200 71410
[2022-06-20 10:04:39,114] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2022-06-20 10:04:39,254] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2022-06-20 10:04:39,529] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2022-06-20 10:04:39,533] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2022-06-20 10:04:40,270] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 22499
[2022-06-20 10:04:40,440] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 10:04:40 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 10:04:40,451] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 47667
[2022-06-20 10:04:44,080] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 10:04:44 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 10:04:44,090] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 4093
[2022-06-20 10:04:57,699] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 10:04:57 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 10:04:57,724] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 4103
[2022-06-20 10:06:29,129] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 10:06:29 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 10:06:29,141] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 4103
[2022-06-20 10:07:59,996] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 10:07:59 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 10:08:00,006] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 4103
[2022-06-20 10:08:17,725] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 22499
[2022-06-20 10:08:18,327] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 22499
[2022-06-20 10:08:25,923] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /PersonalInfo/Summary3/ HTTP/1.1" 200 71410
[2022-06-20 10:08:27,285] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 22499
[2022-06-20 10:08:27,716] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 10:08:27 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 10:08:27,730] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 47667
[2022-06-20 10:08:35,170] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 10:08:35 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 10:08:35,181] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 4103
[2022-06-20 10:08:53,973] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 10:08:53 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 10:08:54,000] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 4093
[2022-06-20 10:09:05,545] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2022-06-20 10:09:05,545] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2022-06-20 10:09:05,561] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2022-06-20 10:09:05,599] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2022-06-20 10:09:08,794] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 10:09:08 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 10:09:08,805] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 4093
[2022-06-20 10:09:14,428] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 10:09:14 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 10:09:14,439] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 4103
[2022-06-20 10:14:13,596] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 22499
[2022-06-20 10:14:14,151] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 22499
[2022-06-20 10:14:29,272] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /PersonalInfo/Summary3/ HTTP/1.1" 200 71410
[2022-06-20 10:14:30,262] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 22499
[2022-06-20 10:14:30,642] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 10:14:30 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 10:14:30,648] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 47667
[2022-06-20 10:14:42,928] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 10:14:42 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 10:14:42,934] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 4103
[2022-06-20 10:14:53,867] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 10:14:53 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 10:14:53,879] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 4113
[2022-06-20 10:14:59,001] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 10:14:59 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 10:14:59,013] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 4117
[2022-06-20 10:15:36,857] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 10:15:36 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 10:15:36,952] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 4117
[2022-06-20 10:15:48,700] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 10:15:48 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 10:15:48,717] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 4115
[2022-06-20 10:16:03,155] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /PersonalInfo/Summary3/ HTTP/1.1" 200 71410
[2022-06-20 10:16:04,759] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 22499
[2022-06-20 10:16:05,003] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 10:16:05 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 10:16:05,011] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 47667
[2022-06-20 10:16:16,609] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2022-06-20 10:16:16,612] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2022-06-20 10:16:16,684] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2022-06-20 10:16:16,765] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2022-06-20 10:16:20,170] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /PersonalInfo/Summary3/ HTTP/1.1" 200 71410
[2022-06-20 10:16:20,649] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2022-06-20 10:16:20,777] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2022-06-20 10:16:21,369] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2022-06-20 10:16:21,403] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2022-06-20 10:16:22,873] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 22499
[2022-06-20 10:16:23,037] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 10:16:23 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 10:16:23,058] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 47667
[2022-06-20 10:16:43,408] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 10:16:43 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 10:16:43,419] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 4113
[2022-06-20 10:17:06,465] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 10:17:06 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 10:17:06,478] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 4117
[2022-06-20 10:17:15,172] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 10:17:15 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 10:17:15,187] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 4127
[2022-06-20 10:18:31,491] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /PersonalInfo/Summary3/ HTTP/1.1" 200 71410
[2022-06-20 10:18:31,726] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2022-06-20 10:18:31,921] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2022-06-20 10:18:32,242] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2022-06-20 10:18:32,292] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2022-06-20 10:18:33,563] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 22499
[2022-06-20 10:18:33,782] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 10:18:33 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 10:18:33,790] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 47667
[2022-06-20 10:18:51,740] [UserIP.py:87] [UserIP:process_response] [INFO]- 2022-06-20 10:18:51 C1010S3>Edwin None>LAPTOP-1EJQO0D7>311 127.0.0.1 127.0.0.1 /PersonalInfo/Summary3/ POST
[2022-06-20 10:18:51,747] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /PersonalInfo/Summary3/ HTTP/1.1" 200 4117
