[2023-02-06 13:59:54,875] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /PersonalInfo/PersonalInfo-search/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\PersonalInfo\views.py", line 764, in PersonalInfo_search
    float(str((i["LastPromotionData"] - LastLastPromotionData)).split(' ')[0]) / 365, 1),
TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.date'
[2023-02-06 13:59:54,884] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /PersonalInfo/PersonalInfo-search/ HTTP/1.1" 500 94410
[2023-02-06 14:03:37,640] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /PersonalInfo/PersonalInfo-search/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\PersonalInfo\views.py", line 764, in PersonalInfo_search
    float(str((i["LastPromotionData"] - LastLastPromotionData)).split(' ')[0]) / 365, 1),
TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.date'
[2023-02-06 14:03:37,655] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /PersonalInfo/PersonalInfo-search/ HTTP/1.1" 500 94410
[2023-02-06 14:04:28,473] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /PersonalInfo/PersonalInfo-search/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\PersonalInfo\views.py", line 764, in PersonalInfo_search
    float(str((i["LastPromotionData"] - LastLastPromotionData)).split(' ')[0]) / 365, 1),
TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.date'
[2023-02-06 14:04:28,478] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /PersonalInfo/PersonalInfo-search/ HTTP/1.1" 500 94410
[2023-02-06 14:08:36,676] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /PersonalInfo/PersonalInfo-search/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\PersonalInfo\views.py", line 764, in PersonalInfo_search
    float(str((i["LastPromotionData"] - LastLastPromotionData)).split(' ')[0]) / 365, 1),
TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.date'
[2023-02-06 14:08:36,677] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /PersonalInfo/PersonalInfo-search/ HTTP/1.1" 500 94410
[2023-02-06 14:08:41,892] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /PersonalInfo/PersonalInfo-search/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\PersonalInfo\views.py", line 764, in PersonalInfo_search
    float(str((i["LastPromotionData"] - LastLastPromotionData)).split(' ')[0]) / 365, 1),
TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.date'
[2023-02-06 14:08:41,898] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /PersonalInfo/PersonalInfo-search/ HTTP/1.1" 500 94410
[2023-02-06 14:08:48,252] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /PersonalInfo/PersonalInfo-search/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\PersonalInfo\views.py", line 764, in PersonalInfo_search
    float(str((i["LastPromotionData"] - LastLastPromotionData)).split(' ')[0]) / 365, 1),
TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.date'
[2023-02-06 14:08:48,256] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /PersonalInfo/PersonalInfo-search/ HTTP/1.1" 500 94410
