[2020-09-02 08:52:55,665] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /CQM/CQM_edit/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1735, in add_fields
    join_info = self.setup_joins(name.split(LOOKUP_SEP), opts, alias, allow_many=allow_m2m)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1473, in setup_joins
    names[:pivot], opts, allow_many, fail_on_missing=True,
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1389, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'Phase' into field. Choices are: Customer, Owner, Project, cqm, id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\CQM\views.py", line 405, in CQM_edit
    for i in CQMProject.objects.filter(Customer=Customer).values("Project","Phase").distinct().order_by(
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 750, in values
    clone = self._values(*fields, **expressions)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 745, in _values
    clone.query.set_values(fields)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1987, in set_values
    self.add_fields(field_names, True)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1758, in add_fields
    "Choices are: %s" % (name, ", ".join(names)))
django.core.exceptions.FieldError: Cannot resolve keyword 'Phase' into field. Choices are: Customer, Owner, Project, cqm, id
[2020-09-02 08:52:55,668] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /CQM/CQM_edit/ HTTP/1.1" 500 118953
[2020-09-02 08:58:12,220] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /CQM/CQM_edit/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\CQM\views.py", line 412, in CQM_edit
    for j in CQM.objects.filter(Project=i).values('Phase').disrinct.order_by("Phase"):
AttributeError: 'QuerySet' object has no attribute 'disrinct'
[2020-09-02 08:58:12,223] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /CQM/CQM_edit/ HTTP/1.1" 500 81063
[2020-09-02 08:58:41,093] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /CQM/CQM_edit/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\CQM\views.py", line 412, in CQM_edit
    for j in CQM.objects.filter(Project=i).values('Phase').distinct.order_by("Phase"):
AttributeError: 'function' object has no attribute 'order_by'
[2020-09-02 08:58:41,096] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /CQM/CQM_edit/ HTTP/1.1" 500 81063
[2020-09-02 09:09:11,868] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /CQM/CQM_edit/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\CQM\views.py", line 374, in CQM_edit
    Projectinfo = CQMProject.objects.filter(**Check_dic_Project).first()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1164, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1028, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1389, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'Phase' into field. Choices are: Customer, Owner, Project, cqm, id
[2020-09-02 09:09:11,871] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /CQM/CQM_edit/ HTTP/1.1" 500 120636
[2020-09-02 09:17:44,964] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /CQM/CQM_edit/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\CQM\views.py", line 451, in CQM_edit
    Phase = resdatas['Phase']
KeyError: 'Phase'
[2020-09-02 09:17:44,966] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /CQM/CQM_edit/ HTTP/1.1" 500 82437
