[2020-03-17 08:22:46,317] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MQM/MQM_edit/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MQM\views.py", line 263, in MQM_edit
    print(editPpriority)
UnboundLocalError: local variable 'editPpriority' referenced before assignment
[2020-03-17 08:22:46,333] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /MQM/MQM_edit/ HTTP/1.1" 500 27
