[2021-11-04 08:32:01,241] [UserIP.py:89] [UserIP:process_response] [CRITICAL]- 系统错误
[2021-11-04 13:56:15,308] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /DeviceLNV/M_Return/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\DMS\DeviceLNV\views.py", line 3265, in M_Return
    updatedic['uscyc'] = str(int(DeviceLNV.objects.filter(id=i).first().uscyc) + int(DeviceLNV.objects.filter(id=i).first().Last_uscyc))
ValueError: invalid literal for int() with base 10: ' '
[2021-11-04 13:56:15,313] [UserIP.py:89] [UserIP:process_response] [CRITICAL]- 系统错误
[2021-11-04 13:56:15,314] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /DeviceLNV/M_Return/ HTTP/1.1" 500 80098
[2021-11-05 07:56:14,056] [UserIP.py:89] [UserIP:process_response] [CRITICAL]- 系统错误
[2021-11-05 07:56:26,989] [UserIP.py:89] [UserIP:process_response] [CRITICAL]- 系统错误
[2021-11-05 07:58:55,945] [UserIP.py:89] [UserIP:process_response] [CRITICAL]- 系统错误
